version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      build-tools:
        patterns: ["electron", "electron-builder"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
